### ISSUE TITLE
FIRST ISSUE

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/conversion_collab_vanillaJS#2]
To complete this issue you need to create the following: 

- [x] main container which is going to be centered on the screen 
- [x] header centered in container "Currency Converter" 
- [x] input where user will input the value 
- [x] two select dropdowns, one for origin currency and other for desired currency 
- [x] button for firing function conversion

**Comment by nedimmujcinovic** [comment]
I'm done all tasks from this issue.
